\version "2.24.0"
\header {
  title = "Recorded MIDI Performance"
  composer = "Generated by KeyWorks"
  tagline = "Created on 2025-03-05"
}

\score {
  \new Staff {
    \clef treble
    \time 4/4
    \tempo 4 = 120

    c'16 d'16 e'16 f'16 g'16 a'16 b'16 b'8 c''2 d'2 e'4 
  }
  \layout { }
  \midi { }
}
