\version "2.24.0"
\header {
  title = "Recorded MIDI Performance"
  composer = "Generated by KeyWorks"
  tagline = "Created on 2025-03-05"
}

\score {
  \new Staff {
    \clef treble
    \time 4/4
    \tempo 4 = 120

    c'4 d'4 e'4 f'4 g'4 a'4 b'4 c''4 
  }
  \layout { }
  \midi { }
}
